Repository tuneinsight/glowing-bear-medco, pull requests merged in 2022-09, with the labels that each got.

#58 Display units
  src/app/modules/gb-explore-module/constraint-components/gb-concept-constraint/gb-concept-constraint.component.html
  src/app/services/tree-node.service.ts
Labels: bug

#60 Align "Allowed Result Type" to the left
  src/app/modules/gb-explore-module/gb-explore.component.html
Labels: enhancement

#57 Network health
  src/app/models/api-response-models/medco-network/api-network-status-metadata.ts
  src/app/models/api-response-models/medco-network/api-node-metadata.ts
  src/app/modules/gb-explore-module/gb-explore.component.ts
  src/app/modules/gb-select-project-module/gb-select-project.component.ts
  src/app/modules/gb-side-panel-module/accordion-components/gb-summary/gb-summary.component.css
  src/app/modules/gb-side-panel-module/accordion-components/gb-summary/gb-summary.component.html
  src/app/modules/gb-side-panel-module/accordion-components/gb-summary/gb-summary.component.ts
  src/app/services/api/medco-network.service.ts
  src/app/services/tree-node.service.ts
Labels: enhancement

#59 Update readme
  README.md
Labels: documentation

#66 Fix mode selection bug
  package-lock.json
  src/app/app.module.ts
  src/app/modules/gb-main-module/gb-main.component.ts
  src/app/modules/gb-select-project-module/gb-select-project.component.ts
  src/app/services/api/medco-node/explore-query.service.ts
  src/app/services/navbar.service.ts
  src/app/services/tree-node.service.ts
Labels: bug
